const minors = [
  'Aerospace Engineering',
  'Africana Studies',
  'American Indian and Indigenous Studies',
  'American Studies',
  'Animal Science',
  'Anthropology',
  'Applied Economics',
  'Applied Exercise Science',
  'Applied Mathematics',
  'Arabic',
  'Archaeology',
  'Architecture',
  'Asian American Studies',
  'Astrobiology',
  'Astronomy',
  'Atmospheric Science',
  'Biological Engineering',
  'Biological Sciences',
  'Biomedical Engineering',
  'Biomedical Sciences',
  'Biometry and Statistics',
  'Business',
  'China and Asia-Pacific Studies',
  'Civil Infrastructure',
  'Classical Civilization',
  'Classics',
  'Climate Change',
  'Cognitive Science',
  'Communication',
  'Community Food Systems',
  'Comparative Literature',
  'Computer Science',
  'Computing in the Arts',
  'Creative Writing',
  'Crime, Prisons, Education, and Justice',
  'Crop Management',
  'Dance',
  'Data Science in Astronomy',
  'Demography',
  'Design & Environmental Analysis',
  'Development Sociology',
  'Dyson Business Minor for Engineers',
  'Dyson Business Minor for Life Sciences Majors',
  'Earth and Atmospheric Sciences',
  'East Asian Studies',
  'English',
  'Education',
  'Electrical and Computer Engineering',
  'Engineering Entrepreneurship',
  'Engineering Management',
  'Engineering Statistics',
  'Entrepreneurship and Innovation',
  'Entomology',
  'Environmental, Energy, & Resource Economics',
  'Environmental Engineering',
  'Environment & Sustainability',
  'European Studies',
  'Feminist, Gender, & Sexuality Studies',
  'Fiber Science',
  'Film',
  'Fine Arts',
  'Food and Agricultural Business',
  'Food Science',
  'French',
  'Fungal Biology',
  'Game Design',
  'German Studies',
  'Gerontology',
  'Global Health',
  'Health Policy',
  'History',
  'History of Art',
  'History of Capitalism',
  'Horticulture',
  'Human Development',
  'Industrial Systems & Information Technology',
  'Inequality Studies',
  'Infectious Disease Biology',
  'Information Science',
  'International Relations',
  'International Development Studies',
  'International Trade & Development',
  'Italian Studies',
  'Jewish Studies',
  'Landscape Studies',
  'Latin American Studies',
  'Latina/o Studies',
  'Law and Society',
  'Leadership',
  'Lesbian, Gay, Bisexual, & Transgender Studies',
  'Linguistics',
  'Marine Biology',
  'Materials Science and Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Media Studies',
  'Medieval Studies',
  'Minority, Indigenous, and Third World Studies',
  'Music',
  'Near Eastern Studies',
  'Nutrition & Health',
  'Operations Research & Management Science',
  'Performing and Media Arts',
  'Philosophy',
  'Physics',
  'Plant Breeding',
  'Plant Sciences',
  'Policy Analysis and Management',
  'Portuguese and Brazilian Studies',
  'Psychology',
  'Public Policy',
  'Public Service Studies',
  'Real Estate',
  'Religious Studies',
  'Robotics',
  'Russian',
  'Sanskrit Studies',
  'Science Communication and Public Engagement',
  'Science & Technology Studies',
  'Soil Science',
  'South Asian Studies',
  'Southeast Asian Studies',
  'Spanish',
  'Sustainable Energy Systems',
  'Theatre',
  'Urban and Regional Studies',
  'Viking Studies',
  'Visual Studies',
  'Viticulture and Enology',
]

export default minors
